image_test: "data/input/product_f.jpg"

output_dir: "data/output"

threshold: 80

#Configurações banco de dados
database:
  dbname: "infinity_vision_db"
  user: "postgres"
  password: "@123456@"
#Se container usar:
  host: "db"
 #Se local usar:
 #host: "localhost" 
  port: 5432