#Configuração imagens
image_1: "data/input/product_c.jpg"
image_2: "data/input/product_d.jpg"

output_dir: "data/output"

threshold: 80

#Configurações banco de dados
database:
  dbname: "infinity_vision_db"
  user: "seu-usuario"
  password: "sua-senha"
  host: "localhost"
  port: 5432